### ISSUE TITLE
[Bug] onnx optimize fail with onnxslim

### ISSUE THREAD

**Issue by czdelete** [tsingmicro-toolchain/OnnxSlim#4]
(venv) PS E:\algodebug\efficientV2_item1> onnxslim model_final_dict.onnx output_model_onnxslim.onnx
Traceback (most recent call last):
  File "E:\python3.9.8\pythoninstall\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\python3.9.8\pythoninstall\lib\runpy.py", line 87, in _run_code
  File "E:\algodebug\efficientV2_item1\venv\lib\site-packages\onnxslim\core\optimizer.py", line 769, in optimize_model
    fusion_pairs = find_matches(graph, fusion_patterns)
  File "E:\algodebug\efficientV2_item1\venv\lib\site-packages\onnxslim\core\optimizer.py", line 743, in find_matches
    matches = func(node, opset)
  File "E:\algodebug\efficientV2_item1\venv\lib\site-packages\onnxslim\core\optimizer.py", line 122, in find_conv_nodes
    pad_value = pad_node.inputs[1].values.tolist()
AttributeError: 'Variable' object has no attribute 'values'
(venv) PS E:\algodebug\efficientV2_item1>

**Comment by inisis** [comment]
Hi, this [release ](https://github.com/WeLoveAI/OnnxSlim/releases/tag/v0.1.19)helps fix it, please reinstall onnxslim>=0.1.19
